CREATE TABLE MATCH_BUILD
(
    EUP_MYUN_DONG_CODE       VARCHAR2(30),
    SI_DO_NM                 VARCHAR2(120),
    SI_GUN_GU_NM             VARCHAR2(120),
    EUP_MYUN_DONG_NM         VARCHAR2(120),
    ROAD_NM_CODE             VARCHAR2(12),
    ROAD_NM                  VARCHAR2(240),
    UNDER_YN                 VARCHAR2(3),
    BUILDING_MAIN            NUMBER,
    BUILDING_SUB             NUMBER,
    ZIP_CODE                 NUMBER,
    MANAGEMENT_NO            VARCHAR2(75) PRIMARY KEY,
    SI_GUN_GU_BUILDING       VARCHAR2(120),
    BUILDING_SEP             VARCHAR2(300),
    ADMIN_DONG_CODE          VARCHAR2(30),
    ADMIN_DONG_NAME          VARCHAR2(120),
    UPPER                    NUMBER,
    LOWER                    NUMBER,
    CO_YN                    VARCHAR2(3),
    BUILDING_COUNT           NUMBER,
    BUILDING_NM_DETAIL       VARCHAR2(300),
    BLD_NM_CHANGE_HISTORY    VARCHAR2(2000),
    BLD_NM_CHANGE_HIS_DETAIL VARCHAR2(2000),
    LIVE_YN                  VARCHAR2(3),
    CENTER_LAT               NUMBER(15, 6),
    CENTER_LON               NUMERIC(15, 6),
    ENT_LAT                  NUMBER(15, 6),
    ENT_LON                  NUMBER(15, 6),
    SI_DO_NM_ENG             VARCHAR2(120),
    SI_GUN_GU_NM_ENG         VARCHAR2(120),
    EUP_MYUN_DONG_NM_ENG     VARCHAR2(120),
    ROAD_NM_ENG              VARCHAR2(240),
    EUP_MYUN_DONG_YN         VARCHAR2(3),
    CHANGE_CODE              VARCHAR2(6)
);