spring:
  main:
    banner-mode: "off"
  application:
    name: JUSO_BATCH
  datasource:
    hikari:
      username: springboot
      password: springboot
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      driver-class-name: oracle.jdbc.OracleDriver
      validationTimeout: 10000
      minimumIdle: 10
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
  batch:
    job:
      enabled: true
chunk:
  size: 500